##################################
# Compilation ShoppingSimulator  #
# Common                         #
##################################

comp:
	find src/ -name "*.java" -print | xargs javac -d build
	jar cvf common.jar -C build tictactoe

